### ISSUE TITLE
Missing releases

### ISSUE THREAD

**Issue by esabol** [kran0/davmail-docker#8]
https://github.com/kran0/davmail-docker/tags is missing the tags for the recent DavMail releases, 6.1.0, 6.2.0, and 6.2.1.

Looks like your latest Dockerfile is using DavMail 6.1.0?

**Comment by kran0** [comment]
There is no need to create a davmail-docker tag for every davmail Release since action https://github.com/kran0/davmail-docker/actions/workflows/build_images.yml does the work automatically and publishes the latest builds as soon as Mikaél publishes them.

I occasionally update the Dockerfile, but this is not required to generate new version builds.

Posts to https://hub.docker.com/r/kran0/davmail-docker/tags?page=1&ordering=last_updated.

**Comment by esabol** [comment]
Oh, I see. Thank you! Sorry for the noise.
